// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfOwTaDbLUX6Ic4ZySymHsWDmfXJXgQLU',
    appId: '1:141554790481:web:186103120be071017cc870',
    messagingSenderId: '141554790481',
    projectId: 'quizer911',
    authDomain: 'quizer911.firebaseapp.com',
    storageBucket: 'quizer911.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4BmVsn4cO9tkoL55EPCmY_2IWssMmG3s',
    appId: '1:141554790481:android:8a34774f9d56d8327cc870',
    messagingSenderId: '141554790481',
    projectId: 'quizer911',
    storageBucket: 'quizer911.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ5Tt1p5k_VeTWRj-jZqXF2NhHWBx18yU',
    appId: '1:141554790481:ios:33ade6096cf6b2b27cc870',
    messagingSenderId: '141554790481',
    projectId: 'quizer911',
    storageBucket: 'quizer911.appspot.com',
    iosBundleId: 'com.quizer911.quizer911',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfOwTaDbLUX6Ic4ZySymHsWDmfXJXgQLU',
    appId: '1:141554790481:web:36c831058ba23b457cc870',
    messagingSenderId: '141554790481',
    projectId: 'quizer911',
    authDomain: 'quizer911.firebaseapp.com',
    storageBucket: 'quizer911.appspot.com',
  );
}
